language: go

go:
        - 1.7.x
        - 1.8.x
        - 1.9.x
        - 1.10.x
        - 1.11.x
        - 1.x

install:
        - go get github.com/d4l3k/messagediff
        - go get github.com/davecgh/go-spew/spew
        - go get github.com/golang/lint/golint
        - go get github.com/twpayne/go-geom
        - go get golang.org/x/net/html/charset

script:
        - go test -v ./...
        - go test -cover -race ./...
        - go vet ./...
        - test -z "$(gofmt -d -s *.go)"
        - golint ./...

sudo: false
